---
# tasks file for tower_setup
  - name: Create docker group
    group:
      name: docker
      state: present

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      groups: docker
      append: yes
    sudo: true

  - name: Install repositories and prereqs
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - epel-release

  - name: Install extra packages
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - docker
      - python-pip
      - git
      - ansible

    # Install latest version when no specific release is set.
  - name: Upgrade latest pip, setuptools, docker, docker-py and docker-compose with pip
    pip:
      name: "{{ item.name }}"
      state: latest
    with_items:
      - { name: pip, version: "latest", install: true }
      - { name: setuptools, version: "latest", install: true }
      - { name: docker, version: "latest", install: true }
      - { name: docker-py, version: "latest", install: true }
      - { name: ansible-tower-cli, version: "latest", install: true }
    when: (item.version=="latest" and item.install)
    ignore_errors: yes

  - name: Start docker
    systemd:
      name: docker
      state: started
      enabled: true

  - name: Get latest docker-compose from docker
    get_url:
      url: https://github.com/docker/compose/releases/download/1.20.0-rc2/docker-compose-Linux-x86_64
      dest: /usr/bin/docker-compose
      mode: 0755

  - name: Get latest gitlab-runner from gitlab
    get_url:
      url: https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
      dest: /usr/bin/gitlab-runner
      mode: 0755 

  - name: Clone awx from github
    git:
      repo: https://github.com/ansible/awx.git
      dest: /opt/awx/
      version: devel

  - name: Check to see if AWX is running on port 80 and returns a status 200
    ignore_errors: true
    uri:
      url: http://localhost:80
    register: localhost

  - name: output status code
    debug:
      var: localhost.status

  - name: Install and run AWX if it's not already running on port 80
    command: ansible-playbook -i inventory install.yml
    args:
      chdir: /opt/awx/installer/
    when:
      - localhost is defined
      - localhost.status != 200
